name: ESP32-C3

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/build_esp32c3.yml"

  push:
    paths:
      - "src/**"
      - ".github/workflows/build_esp32c3.yml"

jobs:
  esp32c3:
    name: esp32c3 ${{ matrix.sketches.name }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        sketches:
          - name: serial
          - name: wifi

        board:
          - fqbn: esp32:esp32:esp32c3
            denko-target: esp32
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            libraries: |
              - name: ESP32Servo
                version: 3.0.6
              - name: IRremote
                version: 4.4.1
              - name: Adafruit NeoPixel
                version: 1.13.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate
        id: generate
        run: echo "path=$(./bin/denko sketch ${{ matrix.sketches.name }} --target ${{ matrix.board.denko-target }})" >> $GITHUB_OUTPUT

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.1
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ matrix.board.libraries }}
          sketch-paths: |
            - ${{ steps.generate.outputs.path }}
