name: RA4M1

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/build_ra4m1.yml"

  push:
    paths:
      - "src/**"
      - ".github/workflows/build_ra4m1.yml"

jobs:
  renesas_uno_minima:
    name: ra4m1 ${{ matrix.sketches.name }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        sketches:
          - name: serial
          - name: ethernet
          - name: wifi

        board:
          - fqbn: arduino:renesas_uno:minima
            denko-target: ra4m1
            platforms: |
              - name: arduino:renesas_uno
            libraries: |
              - name: Servo
              - name: Ethernet
              - name: WiFi
              - name: Adafruit NeoPixel
                version: 1.13.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate
        id: generate
        run: echo "path=$(./bin/denko sketch ${{ matrix.sketches.name }} --target ${{ matrix.board.denko-target }})" >> $GITHUB_OUTPUT

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.1
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ matrix.board.libraries }}
          sketch-paths: |
            - ${{ steps.generate.outputs.path }}
