name: Build / RA4M1

on:
  workflow_dispatch:
  
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/build_ra4m1.yml'

  push:
    paths:
      - 'src/**'
      - '.github/workflows/build_ra4m1.yml'
      
jobs:
  samd-zero:
    name: samd ${{ matrix.sketches.name }}
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sketches:
          - name: serial
          - name: ethernet
          - name: wifi
            
        board:
          - fqbn: arduino:renesas_uno:minima
            denko-target: ra4m1
            platforms: |
              - name: arduino:renesas_uno
            libraries: |
              - name: Servo
              - name: Ethernet
              - name: WiFi
              - name: Adafruit NeoPixel
                
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Generate
        id: generate
        run: echo "path=$(./bin/denko sketch ${{ matrix.sketches.name }} --target ${{ matrix.board.denko-target }})" >> $GITHUB_OUTPUT

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.0
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ matrix.board.libraries }}
          sketch-paths: |
            - ${{ steps.generate.outputs.path }}
