name: ATmega AVR

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/build_atmega_avr.yml"

  push:
    paths:
      - "src/**"
      - ".github/workflows/build_atmega_avr.yml"

jobs:
  avr_uno:
    name: atmega avr ${{ matrix.sketches.name }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        sketches:
          - name: serial
          - name: ethernet
          - name: wifi

        board:
          - fqbn: arduino:avr:uno
            denko-target: atmega
            platforms: |
              - name: arduino:avr
            libraries: |
              - name: Servo
              - name: IRremote
                version: 4.4.2
              - name: Ethernet
              - name: WiFi
              - name: Adafruit NeoPixel
                version: 1.15.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate
        id: generate
        run: echo "path=$(./bin/denko sketch ${{ matrix.sketches.name }} --target ${{ matrix.board.denko-target }})" >> $GITHUB_OUTPUT

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.1
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: ${{ matrix.board.libraries }}
          sketch-paths: |
            - ${{ steps.generate.outputs.path }}
